### ISSUE TITLE
Public Response, on Each Project

### ISSUE THREAD

**Issue by michguo** [delhigov/manifesto-tracker#30]
ministry mapping (excel spreadsheet)
allow users to submit a grievance, email
ID or phone number or address etc etc
filter, public (anonymous), possibly also show support

**Comment by srrvnn** [comment]
working on this one now. i am building a form, that anyone can use to post a response

the form will contain: 1) response type (work done, work not visible, corruption report etc. 2) response text 3) links to supporting material.

all response from this form will have to be visible as a list to admin-volunteers, who can mark it for forward or make it public. to prevent spam i am also thinking that when a volunteer marks something as not spam, a response should be publicly visible one week later. one week later to avoid spammers.

**Comment by srrvnn** [comment]
done.
